=== osawa-koki/fractal-explorer.cpp/config.xsd
<?xml version="1.0" encoding="utf-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:simpleType name="HexColor">
  <xsd:restriction base="xsd:hexBinary">
    <xsd:length value="3"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:element name="config">
  <xsd:complexType>
    <xsd:sequence>

      <xsd:element name="width" type="xsd:nonNegativeInteger" />
      <xsd:element name="height" type="xsd:nonNegativeInteger" />
      <xsd:element name="output_directory" type="xsd:string" />

      <xsd:element name="mandelbrot">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="x_min" type="xsd:float" />
            <xsd:element name="x_max" type="xsd:float" />
            <xsd:element name="y_min" type="xsd:float" />
            <xsd:element name="y_max" type="xsd:float" />
            <xsd:element name="threshold" type="xsd:nonNegativeInteger" />
            <xsd:element name="max_iterations" type="xsd:nonNegativeInteger" />
            <xsd:element name="color_hue" type="xsd:nonNegativeInteger" />
            <xsd:element name="output_file" type="xsd:string" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name="julia">
        <xsd:complexType>
          <xsd:sequence>

            <xsd:element name="x_min" type="xsd:float" />
            <xsd:element name="x_max" type="xsd:float" />
            <xsd:element name="y_min" type="xsd:float" />
            <xsd:element name="y_max" type="xsd:float" />
            <xsd:element name="cx" type="xsd:float" />
            <xsd:element name="cy" type="xsd:float" />
            <xsd:element name="threshold" type="xsd:nonNegativeInteger" />
            <xsd:element name="max_iterations" type="xsd:nonNegativeInteger" />
            <xsd:element name="color_hue" type="xsd:nonNegativeInteger" />
            <xsd:element name="output_file" type="xsd:string" />

          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:schema>

=== osawa-koki/fractal-explorer.cpp/config.xml
<?xml version="1.0" encoding="utf-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

  <width>512</width>
  <height>512</height>
  <output_directory>./dist</output_directory>

  <mandelbrot>
    <x_min>-2.2</x_min>
    <x_max>0.8</x_max>
    <y_min>-1.5</y_min>
    <y_max>1.5</y_max>
    <threshold>20</threshold>
    <max_iterations>100</max_iterations>
    <color_hue>0</color_hue>
    <output_file>mandelbrot.png</output_file>
  </mandelbrot>

  <julia>
    <x_min>-1.5</x_min>
    <x_max>1.5</x_max>
    <y_min>-1.5</y_min>
    <y_max>1.5</y_max>
    <cx>-0.4</cx>
    <cy>0.6</cy>
    <threshold>25</threshold>
    <max_iterations>80</max_iterations>
    <color_hue>0</color_hue>
    <output_file>julia.png</output_file>
  </julia>

</config>
